language: ruby
rvm:
  - "2.1.4"

before_script:
  - psql -c "create database gypper_test;" -U postgres

script:
  - bundle exec rake test

deploy:
  provider: heroku
  api_key: "7c03744a91dcaea828329dfb5d45246a727b412f"
  on: master
  app: gypper
  run: "rake db:migrate"